name: Checkout and NodeJS
on: 
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        token: ${{ github.token }}
        show-progress: true
        path: '.'
        ref: 'support'    
    - name: Install Dependencies
      run: npm install
